docs_dir: markdown
pages:
- Home: index.md
- Workflows:
  - Ansible: ANSIBLE.md
  - Build: BUILD.md
  - Docker: DOCKER.md
  - Documentation: DOCUMENTATION.md
  - Email: EMAIL.md
  - Fpm: FPM.md
  - Git: GIT.md
  - Github: GITHUB.md
  - Golang: GOLANG.md
  - Gradle: GRADLE.md
  - Nodejs: NODEJS.md
  - Python: PYTHON.md
  - Rust: RUST.md
  - Slack: SLACK.md
- About:
  - Changelog: CHANGELOG.md
site_dir: docs
site_name: jenkins-workflows
theme:
  name: material
